import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { BOSS_QUESTS, QUESTS } from "../src/data.js";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(
  projectRoot,
  "supabase/migrations/202607120003_quest_catalog_seed.sql"
);

function sqlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function row(quest) {
  return [
    sqlString(quest.id),
    quest.level,
    sqlString(quest.statType),
    quest.energyCost,
    quest.rewardEnergy || 0,
    Boolean(quest.isShadow),
    Boolean(quest.isBoss),
    sqlString(quest.questText),
    sqlString(quest.lowPressureVariant),
    sqlString(quest.advancedVariant),
    true,
    1
  ].join(", ");
}

export function buildSupabaseQuestSeed() {
  const quests = [...QUESTS, ...BOSS_QUESTS];
  const values = quests.map((quest) => `  (${row(quest)})`).join(",\n");
  return `-- Generated by scripts/export_supabase_seed.mjs. Do not edit manually.\n` +
    `insert into public.quests_pool_cloud (\n` +
    `  id, level, stat_type, energy_cost, reward_energy, is_shadow, is_boss,\n` +
    `  quest_text, low_pressure_variant, advanced_variant, safety_reviewed, content_version\n` +
    `) values\n${values}\n` +
    `on conflict (id) do update set\n` +
    `  level = excluded.level,\n` +
    `  stat_type = excluded.stat_type,\n` +
    `  energy_cost = excluded.energy_cost,\n` +
    `  reward_energy = excluded.reward_energy,\n` +
    `  is_shadow = excluded.is_shadow,\n` +
    `  is_boss = excluded.is_boss,\n` +
    `  quest_text = excluded.quest_text,\n` +
    `  low_pressure_variant = excluded.low_pressure_variant,\n` +
    `  advanced_variant = excluded.advanced_variant,\n` +
    `  safety_reviewed = excluded.safety_reviewed,\n` +
    `  content_version = excluded.content_version,\n` +
    `  updated_at = now();\n`;
}

async function main() {
  const expected = buildSupabaseQuestSeed();
  if (process.argv.includes("--check")) {
    const actual = await readFile(outputPath, "utf8");
    if (actual !== expected) throw new Error(`Generated Supabase seed is stale: ${outputPath}`);
    console.log(`Verified Supabase seed: ${QUESTS.length} quests, ${BOSS_QUESTS.length} bosses`);
  } else {
    await writeFile(outputPath, expected);
    console.log(`Exported Supabase seed: ${QUESTS.length} quests, ${BOSS_QUESTS.length} bosses`);
  }
}

const isMain =
  process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url;

if (isMain) {
  await main();
}
